package com.dev.core.domain.constant.dbtables;

public enum RefreshStats {
	//Columns related to table REFRESH_STATS
	REFRESH_STATS_ID,
	CLASS_NAME_ID,
	CREATED_DATE,
	TOTAL_REFRESH_COUNT,
	SUCCESS_COUNT,
	SUCCESS_PERCENT,
	SUCCESS_PERCENT_INCR,
	SUCCESS_TREND,
	AGENT_ERROR_COUNT,
	AGENT_ERROR_PERCENT,
	AGENT_ERROR_PERCENT_INCR,
	AGENT_ERROR_TREND,
	SITE_ERROR_COUNT,
	SITE_ERROR_PERCENT,
	SITE_ERROR_PERCENT_INCR,
	SITE_ERROR_TREND,
	UAR_ERROR_COUNT,
	UAR_ERROR_PERCENT,
	UAR_ERROR_PERCENT_INCR,
	UAR_ERROR_TREND,
	INFRA_ERROR_COUNT,
	INFRA_ERROR_PERCENT,
	INFRA_ERROR_PERCENT_INCR,
	INFRA_ERROR_TREND,
	HOUR
}
